<?php

/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: slysak
 * Date: Mon, 04 Apr 2016 11:44:47 +0000
 */

$conf['title'] = 'Проектная вики';
$conf['lang'] = 'ru';
$conf['license'] = '';
$conf['recent_days'] = 31;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin, @ADMINISTRATOR';
$conf['defaultgroup'] = 'VIEWER';         // Default groups new Users are added to
$conf['disableactions'] = 'register';
$conf['auth_security_timeout'] = 3600;
$conf['dnslookups'] = 0;
$conf['authtype'] = 'authmantis';

// end auto-generated content
