<?php

/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: slysak
 * Date: Mon, 04 Apr 2016 11:44:47 +0000
 */

$conf['title'] = 'Skynin';
$conf['lang'] = 'ru';
$conf['license'] = 'publicdomain';
$conf['recent_days'] = 31;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin, @ADMINISTRATOR';
$conf['defaultgroup'] = 'VIEWER';         // Default groups new Users are added to
$conf['disableactions'] = 'register';
$conf['auth_security_timeout'] = 3600;
$conf['dnslookups'] = 0;
$conf['authtype'] = 'authmantis';

// end auto-generated content

$pathMantis = preg_replace('/wiki.+conf/i', '', __DIR__);

define( 'MANTIS_ROOT', $pathMantis );  // file path to Mantis, must terminate with /
define( 'MANTIS_URL', $_SERVER['SERVER_NAME'] );     // url to Mantis, must terminate with /

# If selecting the mantis auth backend results in fatal errors from redeclaration of utf8 functions, uncomment this:

require_once( MANTIS_ROOT . 'core.php' );